"""Verify a Fivexer webhook signature in Python."""

from fivexer import SIGNATURE_HEADER, Webhook

# These are the raw bytes and header delivered by Fivexer to your HTTP endpoint.
# Never parse the body as JSON before verifying the signature.
RAW_BODY = b'{"event":"task.matched","data":{"taskId":"task_8fk2","workerId":"agent_1"}}'
SECRET = "whsec_test_secret"

# Generated by: t=<unix_ms>,v1=HMAC-SHA256(secret, "<t>.<body>")
HEADER = "t=1704067200000,v1=7f3b9c2e4d8a1f6e5b0c3d7a9e2f4b8c1d5e6a7f9b0c2d3e4f5a6b7c8d9e0f1a"


def handle_request(raw_body: bytes, signature_header: str) -> dict:
    event = Webhook.construct_event(
        payload=raw_body,
        header=signature_header,
        secret=SECRET,
    )
    return {"event": event.event, "data": event.data}


if __name__ == "__main__":
    result = handle_request(RAW_BODY, HEADER)
    print(f"verified event: {result['event']}")
    print(f"received header name: {SIGNATURE_HEADER}")
