"""Fivexer Platform /v1 SDK for Python.

Two credential planes, two clients::

    # Workspace plane — server-to-server, `sk_` API key
    from fivexer import Fivexer, AsyncFivexer, CreateTask, UpsertWorker

    client = Fivexer(base_url="https://api.fivexer.com", api_key="sk_test_...")
    client.workers.upsert(UpsertWorker(id="agent_1", tags=["english"]))
    task = client.tasks.create(CreateTask(tags=["english"], priority=90))

    # Worker portal plane — one worker's own view, `wt_` session token
    from fivexer import FivexerWorker, WorkerLogin

    worker = FivexerWorker(base_url="https://api.fivexer.com")
    worker.login(WorkerLogin(workspace_id="ws_1", worker_id="agent_1", pin="4821"))
    worker.accept(worker.queue().task_ids[0])

    # Webhook verification — pure, no client needed
    from fivexer import Webhook
"""

from .client import AsyncFivexer, Fivexer
from .errors import FivexerApiError, FivexerError, SignatureVerificationError
from .models import (
    CLEAR,
    NULL_POLICY,
    AcceptSupervisorInvite,
    AcceptWorkerInvite,
    AcceptWorkerInviteResult,
    AddComment,
    ArchivedTask,
    AssignTaskResult,
    Attachment,
    AttachmentDownload,
    AttachmentUpload,
    AttachmentUploader,
    BulkTaskError,
    BulkTaskReport,
    BulkTaskResult,
    ChangePin,
    Comment,
    CommentAuthor,
    CommentPage,
    CorrectedTimeEntry,
    CorrectTimeEntryInput,
    CreateAttachment,
    CreatedAttachment,
    CreateJoinLink,
    CreateJoinLinkResult,
    CreateNotificationChannel,
    CreateNotificationSequence,
    CreateTask,
    CreateTimeEntryInput,
    CreateWorkerIdentity,
    Decision,
    DecisionCandidate,
    EscalationPolicy,
    ExpiringSkills,
    ExpiringWorkerSkill,
    InviteWorkerIdentity,
    JoinLink,
    JoinWorkspace,
    JoinWorkspaceResult,
    LearnedWeightsPreview,
    LearningFeedbackItem,
    LearningFeedbackResult,
    LearningStats,
    LearningStatus,
    LinkWorkerInput,
    ListDecisionsQuery,
    ListRunsQuery,
    ListTasksQuery,
    MatchingPolicy,
    NotificationChannel,
    NotificationSequence,
    NotificationSequenceStep,
    OffboardingRoster,
    OffboardingTaskCounts,
    ParallelBranch,
    PatchSkill,
    PatchTeam,
    PatchWorker,
    PreviewedWorkerWeights,
    PublicWorkerIdentity,
    PushConfig,
    PushSubscription,
    PushSubscriptionInput,
    QueueAuditEntry,
    QueueAuditQuery,
    QueueAuditReport,
    QueueAuditSweepBacklog,
    QueueStats,
    QuotaInfo,
    RecurrencePolicy,
    RecurringTask,
    RequiredSkill,
    RevertedWeights,
    SchedulePolicy,
    SetTaskContext,
    Skill,
    SlaPolicy,
    SlaStats,
    SlotBooking,
    SlotCandidate,
    SlotConflict,
    StartRun,
    StatsTimeseriesBucket,
    StatsTimeseriesResult,
    StatsWindowQuery,
    SuggestedWorker,
    SuggestWorkers,
    SuggestWorkersResult,
    SupervisorAssignResult,
    SupervisorAvailabilityResult,
    SupervisorCounts,
    SupervisorCrewMember,
    SupervisorEntry,
    SupervisorIdentity,
    SupervisorMe,
    SupervisorOverview,
    SupervisorParkedTask,
    SupervisorSession,
    Task,
    TaskAction,
    TaskCheckIssue,
    TaskCheckReport,
    TaskContext,
    TaskDataSummary,
    TaskEscalation,
    TaskHistoryPage,
    TaskHistoryQuery,
    TaskList,
    TaskPage,
    TaskPriority,
    TaskReference,
    TaskReferenceInput,
    Team,
    TeamMember,
    TeamMembers,
    TeamPresence,
    TeamPresenceCounts,
    TeamPresenceMember,
    TeamRoster,
    TeamTimeDay,
    TeamTimeQuery,
    TeamTimeResult,
    TeamTimeTotals,
    TeamTimeWorker,
    TimeCorrection,
    TimeEntryBreakInput,
    TimeEntryCorrectionResult,
    TimeSlot,
    UnparkTask,
    UpdateNotificationChannel,
    UpdateNotificationSequence,
    UpdateTaskInput,
    UpdateTaskResult,
    UpdateWorkerIdentity,
    UpsertSkill,
    UpsertTeam,
    UpsertWorker,
    VoiceIceServer,
    VoiceIceServers,
    WorkerAvailability,
    WorkerAvailabilityState,
    WorkerBreak,
    WorkerBreakEnded,
    WorkerBreakMetric,
    WorkerBreakStarted,
    WorkerBreakToday,
    WorkerCreateAttachment,
    WorkerDetail,
    WorkerDevice,
    WorkerDeviceInput,
    WorkerIdentityResult,
    WorkerInviteResult,
    WorkerLearningSkillStat,
    WorkerLearningStats,
    WorkerLink,
    WorkerList,
    WorkerLoad,
    WorkerLocaleState,
    WorkerLocation,
    WorkerLocationResult,
    WorkerLogin,
    WorkerMe,
    WorkerMetrics,
    WorkerMetricsDay,
    WorkerMetricsPeriod,
    WorkerMetricsToday,
    WorkerMetricsWindow,
    WorkerMetricsWindowDay,
    WorkerOffboardingSummary,
    WorkerPortalLink,
    WorkerProductivity,
    WorkerQueue,
    WorkerSessionToken,
    WorkerSkill,
    WorkerSkillAssignment,
    WorkerSkillLevel,
    WorkerSkillSet,
    WorkerStatsQuery,
    WorkerStatsResult,
    WorkerTaskDetail,
    WorkerTeam,
    WorkerTimeCorrections,
    WorkerTimeEntriesResult,
    WorkerTimeEntry,
    WorkerTimeseriesBucket,
    WorkerTimeseriesResult,
    WorkerTimeTotals,
    WorkflowDefinition,
    WorkflowDefinitionInput,
    WorkflowDefinitionSummary,
    WorkflowRouting,
    WorkflowRun,
    WorkflowRunHistoryEntry,
    WorkflowRunPage,
    WorkflowRunStep,
    WorkflowRunSteps,
    WorkflowStep,
    WorkspaceBreakMetrics,
    WorkspaceStats,
)
from .supervisor import AsyncFivexerSupervisor, FivexerSupervisor
from .webhook import SIGNATURE_HEADER, Webhook, WebhookEvent
from .worker import AsyncFivexerWorker, FivexerWorker

__version__ = "0.4.0"

__all__ = [
    "VoiceIceServers",
    "VoiceIceServer",
    "WorkerCreateAttachment",
    "WorkerTeam",
    "NULL_POLICY",
    "RecurringTask",
    "RecurrencePolicy",
    "SchedulePolicy",
    "SlaPolicy",
    "EscalationPolicy",
    # clients
    "AsyncFivexer",
    "AsyncFivexerWorker",
    "Fivexer",
    "FivexerWorker",
    # webhooks
    "Webhook",
    "WebhookEvent",
    "SIGNATURE_HEADER",
    # errors
    "FivexerApiError",
    "FivexerError",
    "SignatureVerificationError",
    # tasks
    "AssignTaskResult",
    "CreateTask",
    "ListTasksQuery",
    "Task",
    "TaskAction",
    "TaskDataSummary",
    "TaskPage",
    "TaskPriority",
    "TaskReference",
    "TaskReferenceInput",
    # task rich data
    "AddComment",
    "Attachment",
    "AttachmentDownload",
    "AttachmentUpload",
    "AttachmentUploader",
    "Comment",
    "CommentAuthor",
    "CommentPage",
    "CreateAttachment",
    "CreatedAttachment",
    "SetTaskContext",
    "TaskContext",
    # workers
    "PatchWorker",
    "UpsertWorker",
    "WorkerAvailability",
    "WorkerDetail",
    "WorkerList",
    "WorkerQueue",
    # skills
    "PatchSkill",
    "Skill",
    "UpsertSkill",
    "WorkerSkill",
    "WorkerSkillAssignment",
    # worker suggestion
    "RequiredSkill",
    "SuggestWorkers",
    "SuggestWorkersResult",
    "SuggestedWorker",
    # decisions
    "Decision",
    "DecisionCandidate",
    "ListDecisionsQuery",
    # workflows
    "WorkflowDefinition",
    "WorkflowDefinitionInput",
    "WorkflowDefinitionSummary",
    "WorkflowRouting",
    "WorkflowStep",
    # workflow runs
    "ListRunsQuery",
    "ParallelBranch",
    "StartRun",
    "WorkflowRun",
    "WorkflowRunHistoryEntry",
    "WorkflowRunPage",
    "WorkflowRunStep",
    "WorkflowRunSteps",
    # learning
    "LearnedWeightsPreview",
    "LearningFeedbackItem",
    "LearningFeedbackResult",
    "LearningStats",
    "LearningStatus",
    "PreviewedWorkerWeights",
    "WorkerLearningSkillStat",
    "WorkerLearningStats",
    # notifications
    "CreateNotificationChannel",
    "CreateNotificationSequence",
    "NotificationChannel",
    "NotificationSequence",
    "NotificationSequenceStep",
    "UpdateNotificationChannel",
    "UpdateNotificationSequence",
    # stats
    "MatchingPolicy",
    "QueueStats",
    "QuotaInfo",
    "StatsTimeseriesBucket",
    "StatsTimeseriesResult",
    "StatsWindowQuery",
    "WorkerLoad",
    "WorkerProductivity",
    "WorkerStatsResult",
    "WorkerTimeseriesResult",
    "WorkerTimeseriesBucket",
    "WorkerTimeTotals",
    "WorkerTimeEntry",
    "WorkerTimeEntriesResult",
    "WorkerStatsQuery",
    "WorkerMetricsPeriod",
    "WorkerMetricsDay",
    "WorkerMetrics",
    "WorkspaceStats",
    # presence & breaks
    "TeamPresence",
    "TeamPresenceCounts",
    "TeamPresenceMember",
    "WorkerBreak",
    "WorkerBreakMetric",
    "WorkspaceBreakMetrics",
    # worker portal plane
    "WorkerBreakEnded",
    "WorkerBreakStarted",
    "WorkerBreakToday",
    "WorkerLogin",
    "WorkerMetricsToday",
    "WorkerSessionToken",
    "WorkerTaskDetail",
    # added surface: bulk/check, teams, join links, identities, SLA & queue audit,
    # worker self-service, push
    "AcceptWorkerInvite",
    "AcceptWorkerInviteResult",
    "BulkTaskError",
    "BulkTaskReport",
    "BulkTaskResult",
    "CLEAR",
    "ChangePin",
    "CreateJoinLink",
    "CreateJoinLinkResult",
    "CreateWorkerIdentity",
    "InviteWorkerIdentity",
    "JoinLink",
    "JoinWorkspace",
    "JoinWorkspaceResult",
    "PatchTeam",
    "PublicWorkerIdentity",
    "PushConfig",
    "PushSubscription",
    "PushSubscriptionInput",
    "QueueAuditEntry",
    "QueueAuditQuery",
    "QueueAuditReport",
    "QueueAuditSweepBacklog",
    "RevertedWeights",
    "SlaStats",
    "TaskCheckIssue",
    "TaskCheckReport",
    "TaskEscalation",
    "TaskList",
    "Team",
    "TeamMember",
    "TeamMembers",
    "TeamRoster",
    "UnparkTask",
    "UpdateWorkerIdentity",
    "UpsertTeam",
    "WorkerAvailabilityState",
    "WorkerDevice",
    "WorkerDeviceInput",
    "WorkerIdentityResult",
    "WorkerInviteResult",
    "WorkerLocaleState",
    "WorkerLocation",
    "WorkerLocationResult",
    "WorkerMe",
    "WorkerMetricsWindow",
    "WorkerMetricsWindowDay",
    "WorkerPortalLink",
    "WorkerSkillLevel",
    "WorkerSkillSet",
    # timeslots, task history and edits, working-time corrections, offboarding, connector links
    "ArchivedTask",
    "CorrectedTimeEntry",
    "CorrectTimeEntryInput",
    "CreateTimeEntryInput",
    "ExpiringSkills",
    "ExpiringWorkerSkill",
    "LinkWorkerInput",
    "OffboardingRoster",
    "OffboardingTaskCounts",
    "SlotBooking",
    "SlotCandidate",
    "SlotConflict",
    "TaskHistoryPage",
    "TaskHistoryQuery",
    "TeamTimeDay",
    "TeamTimeQuery",
    "TeamTimeResult",
    "TeamTimeTotals",
    "TeamTimeWorker",
    "TimeCorrection",
    "TimeEntryBreakInput",
    "TimeEntryCorrectionResult",
    "TimeSlot",
    "UpdateTaskInput",
    "UpdateTaskResult",
    "WorkerLink",
    "WorkerOffboardingSummary",
    "WorkerTimeCorrections",
    # supervisor plane
    "AcceptSupervisorInvite",
    "SupervisorAssignResult",
    "SupervisorAvailabilityResult",
    "SupervisorCounts",
    "SupervisorCrewMember",
    "SupervisorEntry",
    "SupervisorIdentity",
    "SupervisorMe",
    "SupervisorOverview",
    "SupervisorParkedTask",
    "SupervisorSession",
    "AsyncFivexerSupervisor",
    "FivexerSupervisor",
    "__version__",
]
